package staycay.models.enums;

public enum AmenityType {
    WIFI, TV,

    AIR_CONDITIONING, HEATING, FIREPLACE,

    KITCHEN, MICROWAVE, COFFEE_MAKER, DINING_AREA,

    BATHTUB, SHOWER,

    WASHER, DRYER, IRON,

    BALCONY, GARDEN, BBQ, BEACH_ACCESS,

    POOL, HOT_TUB, GYM, SPA, ELEVATOR,

    FREE_PARKING, GARAGE, EV_CHARGER,

    WORKSPACE,

    CRIB,

    PETS_ALLOWED,

    SMOKE_ALARM, SECURITY_SYSTEM,

    STEP_FREE_ACCESS
}